### ISSUE TITLE
Use the Procedure.code and Procedure.category instead of profile tag

### ISSUE THREAD

**Issue by rdingwell** [mcode/rttd-summary-webapp#8]
https://github.com/mcode/rttd-summary-webapp/blob/93d0496656cb9c98edbd324aba93c563b7d25a7c/src/mappingUtils.js#L84

Resources are not guaranteed to have profile tags so we should be using the code and category codes to determine when a procedure is of interest.  Or at the very least not looking for whether it is the first profile in the list but one of the profiles on the resource.

**Comment by Dtphelan1** [comment]
This is addressed for specifically TreatmentPhase, but not more holistically. We have another task for addressing this across the board.
